### PR TITLE
fix(formula): check outputJSON error return in schema command

### PR DESCRIPTION
**Pull request by julianknutsen**
## Problem

`bd formula schema [--json]` (and its `primitives` alias) discarded the error returned by `outputJSON` at two call sites (`cmd/bd/formula_schema.go:46,71`). golangci-lint's **errcheck** flags these, which turned **main red**:

- `Lint` (golangci-lint latest / v2.12.2)
- `PR Lint (wrapper timing)` (v2.9.0)
- `Build Artifacts` (its lint step)

```
cmd/bd/formula_schema.go:46:13: Error return value is not checked (errcheck)
cmd/bd/formula_schema.go:71:13: Error return value is not checked (errcheck)
```

## Fix

Handle the returned error by reporting it to stderr and exiting non-zero, matching the existing `os.Exit(1)` idiom already used a few lines up in `runFormulaSchemaShow`.

## Validation

- `golangci-lint run --timeout=5m --build-tags=gms_pure_go ./...` → **0 issues** (was 2)
- `gofmt -l` clean

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by julianknutsen** [comment]
Superseded by #4623, which fixes all three interlocking CI failures together. Each of these single-axis PRs branched off red main and could never go green on its own (a branch is green only once **all** three axes are fixed).
