### PR TITLE
feat(no-push): guard dolt push/pull and strip push from rendered templates

### PR DESCRIPTION
**Pull request by quad341**
## Summary

Extends the existing `no-push` config option (added in eff58e494) to cover Dolt operations and agent template rendering:

- `bd dolt push` / `bd dolt pull` skip silently (exit 0) when `no-push: true` in config
- `RenderOpts` gains a `NoPush bool`; when `!HasRemote || NoPush`, the `bd dolt push` line is stripped from rendered AGENTS.md templates
- `NoPush` propagated through `AgentsFileParams`, `fs_adapters`, `init`, `setup/agents`, `init_proxied_server`

This is the natural completion of the no-push feature: the existing flag suppressed `git push`, but `bd dolt push` and the template-generated push step were still active in no-push environments.

## Test plan

- [ ] `go test ./cmd/bd/setup/... ./internal/templates/agents/...` — passes
- [ ] `go build ./...` — clean
- [ ] `bd dolt push` on a no-push config returns exit 0 with skip message
- [ ] Generated AGENTS.md omits `bd dolt push` when `NoPush=true`
- [ ] Generated AGENTS.md retains `bd dolt push` when `NoPush=false` (backward compat)
- [ ] Test PR with full unit coverage to follow after this merges

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Review by maphew — COMMENTED** [review]
Found one behavioral issue before this lands:

`cmd/bd/dolt.go:330` now makes `bd dolt pull` return success without contacting the remote whenever `no-push` is true. That changes `no-push` from "do not publish local state" into "do not receive remote state" as well. The documented config contract is narrower: `docs/CONFIG.md` describes `no-push` as "Skip pushing to remote in `bd dolt push`". This matters for read-only or contributor clones that should not push but still need to pull upstream bead updates; after this PR, `bd dolt pull` would print a skip message and leave the local database stale while exiting 0.

I think the `bd dolt push` guard and template stripping are the right direction, but the pull guard should be removed unless we introduce a separate "no sync at all" option. A focused regression test for `bd dolt pull` under `no-push: true` would cover the contract.

Local check: `go test ./internal/templates/agents ./cmd/bd/setup`

_codex-gpt-5.5-medium on behalf of maphew_

**Comment by quad341** [comment]
Thanks for the review. This branch is now merged up to `main`, CI is green (44/44), and the behavioral concern is addressed:

1. **`bd dolt pull` returning success without contacting the remote under `no-push`** — fixed in `f05d07cd`. The guard now lives only on `bd dolt push`; `bd dolt pull` always attempts the pull. Added a focused regression test, `TestNoPushDoesNotSkipDoltPull` (`cmd/bd/dolt_test.go`), asserting that under `no-push: true` the pull is attempted (no "skipping" message). This keeps the documented contract — `no-push` = "Skip pushing to remote in `bd dolt push`" — intact for read-only/contributor clones that still need upstream beads.

Two things resolved since the review so the PR is mergeable:

2. **Merge conflict in `cmd/bd/init.go`** with #4227, which renamed the remote helper to `shouldConfigureInitDoltRemote(..., isDoltLocalOnly())`. Resolved (`bc8ddba5`) by combining both changes — main's `HasRemote` expression plus the new `NoPush` field. `no-push` and `dolt.local-only` are complementary (don't-push-to-an-existing-remote vs. no-remote-wired), not redundant.

3. **`Check doc flags freshness`** went red only after merging `main`'s 1.0.5 docs snapshot (#4246): `website/static/llms-full.txt` needed regenerating, and the committed copy was in non-C-locale order. Regenerated with `LC_ALL=C ./scripts/generate-llms-full.sh` (`07ae3e57f`).

Verified locally: `go build ./...`, `go test ./internal/templates/agents ./cmd/bd/setup`, and the `cmd/bd` init/render suite all pass. Ready for another pass.

**Comment by quad341** [comment]
CI was failing on the **merge result**, not on the branch head itself — a semantic merge conflict with `main`.

`main` had dropped the `"context"` and `internal/storage` imports from `cmd/bd/dolt_test.go` (main's copy of that file no longer referenced them), while this branch added `minimalPullStore`, `fakeRemoteStore`, and `TestNoPushDoesNotSkipDoltPull`, which do use both. GitHub's textually-clean PR-merge kept main's import block but this branch's new usages, so the merge build failed to compile:

```
cmd/bd/dolt_test.go:1477:2: undefined: storage
cmd/bd/dolt_test.go:1482:37: undefined: context
```

Fix: merged `origin/main` into the branch and restored both imports (9ddc99450). Verified locally with the same build configs CI uses:

- `CGO_ENABLED=0 go test -tags gms_pure_go -c ./cmd/bd/` ✓
- `go test -tags gms_pure_go -race -c ./cmd/bd/` ✓
- no-push guard tests pass (`TestNoPushDoesNotSkipDoltPull`, `TestDoltPushPullCommitNeedStore`)

CI is re-running on the updated head now.

**Comment by quad341** [comment]
Rebased this branch onto current `main` and fixed one drift defect that the cached/green checks were hiding.

**What changed**
- Rebased onto current `main` (the branch was ~1 week behind; `main` merged a chain of dolt changes since this PR last ran CI). Net feature diff is unchanged — the no-push guard, `RenderOpts.NoPush`, the template stripping, and `TestNoPushDoesNotSkipDoltPull` are byte-identical to before.
- `cmd/bd/dolt_test.go`: `minimalPullStore` (the fake used by `TestNoPushDoesNotSkipDoltPull`) now implements `ListRemotes`.

**Why the fix was needed**
After this PR was cut, `main` rerouted `bd dolt pull`'s failure handling through `isConfirmedNoRemote(ctx, st, err)`, which calls `st.ListRemotes(ctx)` during error classification (`cmd/bd/dolt.go`). `minimalPullStore` embeds a nil `storage.DoltStorage` and overrode only `Pull`, so once merged into current `main` the test panicked on the new call:

```
panic: runtime error: invalid memory address or nil pointer dereference
  cmd/bd.(*minimalPullStore).ListRemotes
  cmd/bd.isConfirmedNoRemote                cmd/bd/dolt.go:175
  cmd/bd.TestNoPushDoesNotSkipDoltPull      cmd/bd/dolt_test.go
```

This was invisible on GitHub: the green checks were cached from before that refactor landed, and `mergeable=CLEAN` is textual-only. The fake now reports no remotes, which keeps the simulated "remote not found" failure on the benign no-remote path (clean exit, no `os.Exit`) — pull is still attempted, so the test keeps proving the no-push guard does not short-circuit `bd dolt pull`.

**@maphew** — your original point is unchanged and still addressed: the pull guard stays removed, `bd dolt pull` always contacts the remote under `no-push: true`, and `TestNoPushDoesNotSkipDoltPull` passes (now without panicking).

Verified locally against current `main`: `go vet`, `-race` compile, and `CGO_ENABLED=0 go test -tags gms_pure_go ./cmd/bd -run 'TestNoPushDoesNotSkipDoltPull|TestIsConfirmedNoRemote|TestDoltPushPullCommitNeedStore'` plus `./internal/templates/agents ./cmd/bd/setup` all clean. CI re-running on the rebased head.

**Comment by maphew** [comment]
Heads-up on overlap from an upstream review sweep: this PR and #4323 are the same no-push feature (guard `bd dolt push`, leave `bd dolt pull` intact, strip push from rendered templates). #4323 carries a superset of the tests — it adds `TestNoPushSkipsDoltPush` on top of the `TestNoPushDoesNotSkipDoltPull` coverage here.

#4323 was behind `main` and missing the `minimalPullStore.ListRemotes` drift fix you made here, so I rebased it onto current `main` and applied the equivalent fix; it now builds and its no-push tests pass against today's `main`. Given it has both the fix and the extra coverage, the plan is to land #4323 and retire this one to avoid landing the feature twice.

Flagging rather than closing — @maphew, your call on closing this in favor of #4323. Thanks for the original work and the drift diagnosis here; it's what made #4323 straightforward to bring current.

_claude-opus-4-8-high on behalf of maphew_

**Comment by maphew** [comment]
Closing in favor of #4323, which has now merged (fae194f6e).

Both PRs implement the same no-push guard for `bd dolt push`/`pull` plus the rendered-template push stripping, and both are your work, @quad341. #4323 carried the same guard with broader regression coverage (`TestNoPushSkipsDoltPush` / `TestNoPushDoesNotSkipDoltPull` asserting `Push()` is not called and `pull` is not skipped), so it was selected as the landing vehicle. The merged change supersedes this one; no behavior from #4212 is being dropped.

Thanks for the contribution — the credit lands via #4323.

_claude-opus-4-8-high on behalf of maphew_
